from rest_framework import serializers


class ProductSerializer(serializers.Serializer):
    category = serializers.CharField()
    model = serializers.CharField()
    cpu = serializers.CharField()
    cpu_serial = serializers.CharField()
    speed = serializers.FloatField()
    videocard = serializers.CharField()
    ram_type = serializers.CharField()
    ram = serializers.IntegerField()
    hd_type = serializers.CharField()
    hd = serializers.IntegerField()
    diagonal = serializers.FloatField()
    main_cam = serializers.IntegerField()
    back_cam = serializers.CharField()
    front_cam = serializers.CharField()
    color = serializers.CharField()
    os = serializers.CharField()
    price_itbox = serializers.IntegerField()
    price_rozetka = serializers.IntegerField()
    price_citrus = serializers.IntegerField()
    price_allo = serializers.IntegerField()
    price_stylus = serializers.IntegerField()
    itbox_com_count = serializers.IntegerField()
    rozetka_com_count = serializers.IntegerField()
    citrus_com_count = serializers.IntegerField()
    allo_com_count = serializers.IntegerField()
    stylus_com_count = serializers.IntegerField()
