# Generated by Django 3.0.4 on 2020-05-03 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('link_itbox', models.CharField(max_length=250)),
                ('link_rozetka', models.CharField(max_length=250)),
                ('link_citrus', models.CharField(max_length=250)),
                ('link_allo', models.CharField(max_length=250)),
                ('link_stylus', models.CharField(max_length=250)),
                ('img1', models.CharField(max_length=250)),
                ('img2', models.CharField(max_length=250)),
                ('img3', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoxApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(blank=True, max_length=100)),
                ('speed', models.FloatField(blank=True, max_length=25)),
                ('videocard', models.CharField(blank=True, max_length=100)),
                ('ram_type', models.CharField(blank=True, max_length=100)),
                ('ram', models.IntegerField(blank=True)),
                ('hd_type', models.CharField(blank=True, max_length=100)),
                ('hd', models.IntegerField(blank=True)),
                ('diagonal', models.FloatField(blank=True, max_length=25)),
                ('main_cam', models.IntegerField(blank=True)),
                ('back_cam', models.CharField(blank=True, max_length=100)),
                ('front_cam', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('price_itbox', models.IntegerField(blank=True)),
                ('price_rozetka', models.IntegerField(blank=True)),
                ('price_citrus', models.IntegerField(blank=True)),
                ('price_allo', models.IntegerField(blank=True)),
                ('price_stylus', models.IntegerField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoxApp.Category')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoxApp.Contributor')),
            ],
        ),
    ]
