# Generated by Django 3.0.4 on 2020-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoxApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to='./static/Resource'),
            preserve_default=False,
        ),
    ]
